<?xml version="1.0" encoding="UTF-8"?>
<project name="${package(abbrev)}" default="xar">
    <xmlproperty file="expath-pkg.xml" />
    <property name="project.version" value="${package(version)}" />
    <property name="project.app" value="${package(abbrev)}" />
    <property name="build" value="${basedir}/build" />
    <property name="build.dir" value="build" />
    <property name="app.build.dir" value="${build}/${project.app}-${project.version}" /> <!--
    -${data.version} -->

    <target name="clean">
        <echo message="Deleting ${app.build.dir} directory" />
        <delete dir="${app.build.dir}" />
    </target>

    <target name="prepare">
        <mkdir dir="${build}" />
        <mkdir dir="${app.build.dir}" />
        <copy todir="${app.build.dir}">
            <fileset dir="${basedir}">
                <exclude name="${build.dir}" />
                <exclude name="${build.dir}/**" />
                <exclude name=".existdb.json" />
                <exclude name="*.xstrc" />
                <exclude name="local.*" />
                <exclude name="*.build.properties" />
                <exclude name=".github/**" />
                <exclude name=".vs/**" />
                <exclude name=".vscode/**" />
                <exclude name="build.properties" />
                <exclude name=".gitignore" />
                <exclude name="*.code-workspace" />
            </fileset>
        </copy>
    </target>


    <target name="xar">
        <mkdir dir="${build.dir}" />
        <zip basedir="${app.build.dir}"
            destfile="${build.dir}/${project.app}-${project.version}.xar" />
        <copy file="${build.dir}/${project.app}-${project.version}.xar"
            tofile="${build.dir}/${project.app}.xar" overwrite="true" />
    </target>

    <target name="secrets.prepare" depends="prepare">
        <xslt style="secrets.xsl" in="repo.xml" out="${app.build.dir}/repo.xml" force="true" >
            <param name="phase" expression="prepare" />
        </xslt>
    </target>

    <target name="repo.clean">
        <move file="local.repo.xml" tofile="repo.xml" overwrite="true" />
    </target>

</project>